- name: Copy file "{{ extensions_start }}-{{ extensions_end }}.csv"
  template:
    src: "{{ extensions_start }}-{{ extensions_end }}.csv.j2"
    dest: /tmp/{{ extensions_start }}-{{ extensions_end }}.csv
- name: Copy file register.xml
  template:
    src: register.xml.j2
    dest: /tmp/register.xml
- name: Copy file "{{ extensions_start }}-{{ extensions_end }}-0XXXXXXXXX.csv"
  template:
    src: "{{ extensions_start }}-{{ extensions_end }}-0XXXXXXXXX.csv.j2"
    dest: /tmp/{{ extensions_start }}-{{ extensions_end }}-0XXXXXXXXX.csv
- name: Copy file invite-with-auth.xml.j2
  template:
    src: invite-with-auth.xml.j2
    dest: /tmp/invite-with-auth.xml
- name: Copy file invite-without-auth.xml.j2
  template:
    src: invite-without-auth.xml.j2
    dest: /tmp/invite-without-auth.xml
- name: Copy file invite-with-auth-reinvite.xml.j2
  template:
    src: invite-with-auth-reinvite.xml.j2
    dest: /tmp/invite-with-auth-reinvite.xml
- name: Copy config file wav
  copy:
    src: Lost-Star-alaw.wav
    dest: /tmp/Lost-Star-alaw.wav
