- name: Run SIPP invite with auth
  shell:
    cmd: sipp -sf invite-with-auth.xml -inf {{ extensions_start }}-{{ extensions_end }}-0XXXXXXXXX.csv -m {{ total_request }} -r {{ number_of_request_per_second }} -d {{ request_duration }}000 -l {{ number_of_request_per_second|int * request_duration|int }} {{ pbx_server_ip }}
    # cmd: sipp -sf invite-with-auth.xml -inf {{ extensions_start }}-{{ extensions_end }}-0XXXXXXXXX.csv -m {{ total_request }} -r {{ number_of_request_per_second }} -d {{ request_duration }}000  -rtp_echo {{ pbx_server_ip }}
    # cmd: sipp -sf invite-with-auth.xml -inf {{ extensions_start }}-{{ extensions_end }}-0XXXXXXXXX.csv -m {{ total_request }} -r {{ number_of_request_per_second }} -d {{ request_duration }}000 {{ pbx_server_ip }}
    chdir: /tmp/
  ignore_errors: yes
  when: invite_type == "auth"
- name: Run SIPP invite without auth
  shell:
    cmd: sipp -sf invite-without-auth.xml -inf {{ extensions_start }}-{{ extensions_end }}-0XXXXXXXXX.csv -m {{ total_request }} -r {{ number_of_request_per_second }} -d {{ request_duration }}000 -l {{ number_of_request_per_second|int * request_duration|int }} {{ pbx_server_ip }}
    chdir: /tmp/
  ignore_errors: yes
  when: invite_type == "no_auth"
- name: Run SIPP invite with auth and reinvite
  shell:
    cmd: sipp -sf invite-with-auth-reinvite.xml -inf {{ extensions_start }}-{{ extensions_end }}-0XXXXXXXXX.csv -m {{ total_request }} -r {{ number_of_request_per_second }} -d {{ request_duration }}000 -l {{ number_of_request_per_second|int * request_duration|int }} {{ pbx_server_ip }}
    chdir: /tmp/
  ignore_errors: yes
  when: invite_type == "auth_reinvite"